version: "3.7"
# Servicios
services:
    # Aplicación
    app:
        build: .
        depends_on:
            - db
        ports:
            - 80:80
    # Base de datos
    db:
        image: mongo:4.2.10-bionic
        ports:
            - 27017:27017
        volumes: 
            - mongodata:/data/db
# Volumenes
volumes:
    mongodata: